"""
Build an exact join between REST API operations and SDK method coverage.

Two independent signals are combined, because neither is reliable alone:

1. Authoritative signal — literal (HTTP verb, path) pairs parsed straight out
   of the Python and Go SDK source at a given ref. Both SDKs embed the REST
   path as a string literal right next to the HTTP verb
   (Python: `path_template("/cloud/.../{server_id}/action", ...)`,
   Go: `path := fmt.Sprintf("cloud/.../%s/action", ...)`). This is ground
   truth for "does a method exist that calls this path" and is what the
   exhaustive gap check (diff_sdk.py) should trust.

   Known limitation, discovered while validating this tool against the
   DOC-1913 bare-metal-action case: the SDK source can call a path that is
   a renamed alias of the documented spec path (e.g. the SDK's bare-metal
   action call hits `cloud/v2/baremetal/.../action`, while the public spec
   documents `cloud/v2/bminstances/.../action`). An exact string join is
   right in the overwhelming majority of cases, but a "gap" or "no gap"
   verdict from this tool must still go through the live-test step the
   api-use-case skill already requires — this tool narrows down candidates,
   it does not replace verification.

2. Fast signal — `x-codeSamples` already embedded in the OpenAPI spec in
   this repo (generated by the same Stainless/stlc-config pipeline that
   produces the SDKs). Free, network-free, and gives the human-readable
   dotted method name for the doc index join. But it lags real SDK releases
   (confirmed: the current spec still has no Python/Go code sample for the
   bare-metal action endpoint although both SDKs have supported it since
   v0.55.0), so it must not be trusted alone as a gap signal — only used
   for reporting and for the push-triggered fast path.

Output: api-sdk-tracker/endpoint_index.json
"""

import argparse
import json
import logging
import re
import subprocess
import sys
import tempfile
from pathlib import Path

import yaml

logging.basicConfig(level=logging.INFO, format="%(levelname)s %(message)s")
log = logging.getLogger(__name__)

HTTP_METHODS = {"get", "post", "put", "patch", "delete"}
PATH_PARAM_RE = re.compile(r"\{[^{}]+\}")

PY_CALL_RE = re.compile(r"\bclient\.cloud\.((?:\w+\.)+\w+)\s*\(")
GO_CALL_RE = re.compile(r"\bclient\.Cloud\.((?:\w+\.)+\w+)\s*\(")

PY_PATH_RE = re.compile(
    r"self\.(_get|_post|_put|_patch|_delete)\(\s*(?:path_template\(\s*)?[\"']([^\"']+)[\"']"
)
GO_PATH_RE = re.compile(r'path\s*:=\s*(?:fmt\.Sprintf\(\s*)?["\']([^"\']+)["\']')
GO_METHOD_VERB_RE = re.compile(r"http\.Method(\w+)")
GO_VERB_WINDOW = 300

PY_VERB_MAP = {
    "_get": "GET",
    "_post": "POST",
    "_put": "PUT",
    "_patch": "PATCH",
    "_delete": "DELETE",
}

GO_SKIP_DIR_PARTS = {"internal", "option", "shared", "requestconfig", "packages", "vendor"}


def normalize_path(raw_path: str) -> str:
    return PATH_PARAM_RE.sub("{}", raw_path)


def normalize_sdk_path(raw_path: str) -> str:
    """Collapse an SDK-source path literal to the same '{}' placeholder form
    used for OpenAPI paths, regardless of whether it came from Python
    (named {param}) or Go (%v / %s / %d printf verbs), and regardless of a
    missing leading slash (Go paths omit it, Python paths include it)."""
    path = raw_path.strip()
    if not path.startswith("/"):
        path = "/" + path
    path = re.sub(r"%[vsd]", "{}", path)
    path = PATH_PARAM_RE.sub("{}", path)
    return path


def clone_repo_at_ref(url: str, ref: str, dest: Path) -> bool:
    result = subprocess.run(
        ["git", "clone", "--depth", "1", "--branch", ref, url, str(dest)],
        capture_output=True,
        text=True,
    )
    if result.returncode != 0:
        log.warning("Could not clone %s @ %s: %s", url, ref, result.stderr.strip()[-500:])
        return False
    return True


def extract_python_sdk_paths(src_root: Path) -> set[tuple[str, str]]:
    pairs: set[tuple[str, str]] = set()
    resources_dir = src_root / "src" / "gcore" / "resources"
    if not resources_dir.exists():
        return pairs
    for py_file in resources_dir.rglob("*.py"):
        text = py_file.read_text(encoding="utf-8", errors="ignore")
        for m in PY_PATH_RE.finditer(text):
            verb = PY_VERB_MAP[m.group(1)]
            pairs.add((verb, normalize_sdk_path(m.group(2))))
    return pairs


def extract_go_sdk_paths(src_root: Path) -> set[tuple[str, str]]:
    pairs: set[tuple[str, str]] = set()
    for go_file in src_root.rglob("*.go"):
        if go_file.name.endswith("_test.go"):
            continue
        if GO_SKIP_DIR_PARTS & set(go_file.relative_to(src_root).parts):
            continue
        text = go_file.read_text(encoding="utf-8", errors="ignore")
        for m in GO_PATH_RE.finditer(text):
            window = text[m.end() : m.end() + GO_VERB_WINDOW]
            verb_m = GO_METHOD_VERB_RE.search(window)
            if not verb_m:
                continue
            pairs.add((verb_m.group(1).upper(), normalize_sdk_path(m.group(1))))
    return pairs


def fetch_sdk_paths(repo_url: str, ref: str, extractor) -> set[tuple[str, str]] | None:
    """Shallow-clone repo_url at ref into a temp dir and run extractor on it.
    Returns None (rather than an empty set) if the clone fails, so callers
    can distinguish "no coverage" from "signal unavailable"."""
    with tempfile.TemporaryDirectory(prefix="gcore-sdk-") as tmp:
        dest = Path(tmp) / "src"
        if not clone_repo_at_ref(repo_url, ref, dest):
            return None
        return extractor(dest)


def extract_call(code_samples: list, lang: str, prefix: str, call_re: re.Pattern) -> str | None:
    for sample in code_samples:
        if sample.get("lang") != lang:
            continue
        source = sample.get("source", "")
        m = call_re.search(source)
        if m:
            return f"{prefix}.{m.group(1)}"
    return None


def build_product_index(
    spec_path: Path,
    python_sdk_paths: set[tuple[str, str]] | None,
    go_sdk_paths: set[tuple[str, str]] | None,
) -> dict:
    spec = yaml.safe_load(spec_path.read_text(encoding="utf-8"))
    paths = spec.get("paths", {}) or {}

    operations = []
    for raw_path, methods in paths.items():
        if not isinstance(methods, dict):
            continue
        for method, op in methods.items():
            if method.lower() not in HTTP_METHODS or not isinstance(op, dict):
                continue

            http_method = method.upper()
            norm_path = normalize_path(raw_path)
            key = (http_method, norm_path)

            code_samples = op.get("x-codeSamples", []) or []
            python_method = extract_call(code_samples, "Python", "cloud", PY_CALL_RE)
            go_method = extract_call(code_samples, "Go", "Cloud", GO_CALL_RE)

            in_python_sdk = None if python_sdk_paths is None else key in python_sdk_paths
            in_go_sdk = None if go_sdk_paths is None else key in go_sdk_paths

            operations.append(
                {
                    "method": http_method,
                    "path": norm_path,
                    "raw_path": raw_path,
                    "operation_id": op.get("operationId"),
                    "summary": op.get("summary"),
                    "tags": op.get("tags", []),
                    "deprecated": bool(op.get("deprecated", False)),
                    "in_python_sdk": in_python_sdk,
                    "in_go_sdk": in_go_sdk,
                    "has_python_code_sample": python_method is not None,
                    "has_go_code_sample": go_method is not None,
                    "python_method": python_method,
                    "go_method": go_method,
                }
            )

    non_deprecated = [op for op in operations if not op["deprecated"]]
    stats = {
        "total_operations": len(operations),
        "non_deprecated_operations": len(non_deprecated),
        "python_gaps": sum(1 for op in non_deprecated if op["in_python_sdk"] is False),
        "go_gaps": sum(1 for op in non_deprecated if op["in_go_sdk"] is False),
        "python_signal_available": python_sdk_paths is not None,
        "go_signal_available": go_sdk_paths is not None,
    }

    return {"operations": operations, "stats": stats}


def build_lookup_maps(products: dict[str, dict]) -> dict[str, dict]:
    """Reverse maps from SDK dotted method name back to (product, method, path).

    Lets diff_sdk.py resolve a doc_index python_method_to_articles /
    go_method_to_articles key straight to the REST operation it documents.
    """
    python_method_to_operation: dict[str, dict] = {}
    go_method_to_operation: dict[str, dict] = {}

    for product, entry in products.items():
        for op in entry["operations"]:
            ref = {"product": product, "method": op["method"], "path": op["path"]}
            if op["python_method"]:
                python_method_to_operation[op["python_method"]] = ref
            if op["go_method"]:
                go_method_to_operation[op["go_method"]] = ref

    return {
        "python_method_to_operation": python_method_to_operation,
        "go_method_to_operation": go_method_to_operation,
    }


PYTHON_SDK_REPO = "https://github.com/G-Core/gcore-python.git"
GO_SDK_REPO = "https://github.com/G-Core/gcore-go.git"


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--python-ref",
        default="main",
        help="gcore-python git ref (tag or branch) to check SDK coverage against",
    )
    parser.add_argument(
        "--go-ref",
        default="main",
        help="gcore-go git ref (tag or branch) to check SDK coverage against",
    )
    parser.add_argument(
        "--skip-sdk-fetch",
        action="store_true",
        help="Skip cloning SDK repos; only use the spec's x-codeSamples signal "
        "(in_python_sdk/in_go_sdk will be null, not a reliable gap signal)",
    )
    parser.add_argument(
        "--output",
        default=None,
        help="Output path (default: api-sdk-tracker/endpoint_index.json)",
    )
    return parser.parse_args()


def main() -> None:
    args = parse_args()
    repo_root = Path(__file__).parent.parent.parent.parent
    specs_dir = repo_root / "api-reference" / "services_documented"
    output_path = Path(args.output) if args.output else repo_root / "api-sdk-tracker" / "endpoint_index.json"

    if not specs_dir.exists():
        log.error("Specs directory not found: %s", specs_dir)
        sys.exit(2)

    python_sdk_paths: set[tuple[str, str]] | None = None
    go_sdk_paths: set[tuple[str, str]] | None = None

    if not args.skip_sdk_fetch:
        log.info("Fetching gcore-python @ %s ...", args.python_ref)
        python_sdk_paths = fetch_sdk_paths(PYTHON_SDK_REPO, args.python_ref, extract_python_sdk_paths)
        if python_sdk_paths is not None:
            log.info("Found %d (verb, path) pair(s) in gcore-python source", len(python_sdk_paths))

        log.info("Fetching gcore-go @ %s ...", args.go_ref)
        go_sdk_paths = fetch_sdk_paths(GO_SDK_REPO, args.go_ref, extract_go_sdk_paths)
        if go_sdk_paths is not None:
            log.info("Found %d (verb, path) pair(s) in gcore-go source", len(go_sdk_paths))

    products: dict[str, dict] = {}
    for spec_path in sorted(specs_dir.glob("*.yaml")):
        product = spec_path.stem
        try:
            products[product] = build_product_index(spec_path, python_sdk_paths, go_sdk_paths)
        except yaml.YAMLError as exc:
            log.error("Failed to parse %s: %s", spec_path, exc)
            sys.exit(2)

    lookup_maps = build_lookup_maps(products)

    overall = {
        "total_operations": sum(p["stats"]["total_operations"] for p in products.values()),
        "non_deprecated_operations": sum(
            p["stats"]["non_deprecated_operations"] for p in products.values()
        ),
        "python_gaps": sum(p["stats"]["python_gaps"] for p in products.values()),
        "go_gaps": sum(p["stats"]["go_gaps"] for p in products.values()),
        "python_ref": args.python_ref if python_sdk_paths is not None else None,
        "go_ref": args.go_ref if go_sdk_paths is not None else None,
    }

    index = {
        "overall_stats": overall,
        "products": products,
        **lookup_maps,
    }

    output_path.parent.mkdir(parents=True, exist_ok=True)
    output_path.write_text(json.dumps(index, indent=2, ensure_ascii=False), encoding="utf-8")

    log.info(
        "Indexed %d products, %d operations (%d non-deprecated): "
        "%d Python gap(s), %d Go gap(s)",
        len(products),
        overall["total_operations"],
        overall["non_deprecated_operations"],
        overall["python_gaps"],
        overall["go_gaps"],
    )
    log.info("Output: %s", output_path)


if __name__ == "__main__":
    main()
