name: Lint & Deploy

on:
  workflow_dispatch:
  push:
    branches: [ main, dev ]

jobs:
  lint:
    name: Trigger deployment
    runs-on: ubuntu-latest

    steps:
      - env:
          DEPLOY_TARGET: ${{ github.ref_name }}
        run: ${{ secrets.DEPLOY_SCRIPT }}
