name: Lint & Deploy

on:
  - pull_request

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest

    permissions:
      contents: read
      statuses: write

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Lint documentation files
        uses: super-linter/super-linter@v7
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          LINTER_RULES_PATH: '.'
          FILTER_REGEX_INCLUDE: 'documentation/.*\.md'
          VALIDATE_MARKDOWN: true
          MARKDOWN_CONFIG_FILE: '.markdownlint.json'
